times = ('Palmeiras', 'Red Bull Bragantino', 'Athletico Paranaense', 'Atlético Mineiro', 'Fortaleza', 'Bahia', 'Santos', 'Atlético Goianiense', 'Ceará', 'Corinthians', 'Fluminense', 'Flamengo', 'Juventude', 'Internacional', 'América Mineiro', 'São Paulo Futebol Clube', 'Sport Recife', 'Cuiabá', 'Chapecoense', 'Grêmio')
print('='*25)
print(times[0:5])
print('/=/'*25)
print(times[-4:])
print('/=/'*25)
print(sorted(times))
print('/=/'*25)
print(times[-2])
print('='*25)
